### ISSUE TITLE
Импорт passfather не работает 

### ISSUE THREAD

**Issue by saneksa** [vyushin/passfather#19]
Ошибка: `TypeError: (0 , _passfather.default) is not a function` при импорте `import passfather from "passfather";`

Ссылка для воспроизведения: https://codesandbox.io/s/strange-gates-h0nvr?file=/src/App.js

При импорте ` import passfather from "passfather/dist/passfather.js"` все работет нормально

**Comment by vyushin** [comment]
@saneksa, I have fixed this issue. Please, update passfather to 3.0.2 version and try again.
