### ISSUE TITLE
Exclude similar characters

### ISSUE THREAD

**Issue by Amplificator** [vyushin/passfather#22]
Hi.

Is there a way to exclude similar characters such as iI1loO0 ?

**Comment by vyushin** [comment]
Hi, @Amplificator 
At this moment there is only one way to exclude some chars.
1. Turn off all symbols
2. Make your own ranges

Example:
```javascript
const password = passfather({
  numbers: false,
  uppercase: false,
  lowercase: false,
  symbols: false,
  length: 32,
  ranges: [
    [[49, 57]], // Numbers without 0
    [[65, 78], [80, 90]], // Uppercase without O
    [[97, 110], [112, 122]] // Lowercase without o
    // etc...
  ]
})
console.log(password)
```

**Comment by vyushin** [comment]
You can find UTF-8 codes on this page
https://unicode-table.com/ru/#004E
